
package com.javayh.TestClient;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TestService", targetNamespace = "http://impl.webservice.javayh.com/", wsdlLocation = "http://localhost:8089/services/TestService?wsdl")
public class TestService_Service
    extends Service
{

    private final static URL TESTSERVICE_WSDL_LOCATION;
    private final static WebServiceException TESTSERVICE_EXCEPTION;
    private final static QName TESTSERVICE_QNAME = new QName("http://impl.webservice.javayh.com/", "TestService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8089/services/TestService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TESTSERVICE_WSDL_LOCATION = url;
        TESTSERVICE_EXCEPTION = e;
    }

    public TestService_Service() {
        super(__getWsdlLocation(), TESTSERVICE_QNAME);
    }

    public TestService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), TESTSERVICE_QNAME, features);
    }

    public TestService_Service(URL wsdlLocation) {
        super(wsdlLocation, TESTSERVICE_QNAME);
    }

    public TestService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TESTSERVICE_QNAME, features);
    }

    public TestService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServiceImplPort")
    public TestService getTestServiceImplPort() {
        return super.getPort(new QName("http://impl.webservice.javayh.com/", "TestServiceImplPort"), TestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestService
     */
    @WebEndpoint(name = "TestServiceImplPort")
    public TestService getTestServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.webservice.javayh.com/", "TestServiceImplPort"), TestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TESTSERVICE_EXCEPTION!= null) {
            throw TESTSERVICE_EXCEPTION;
        }
        return TESTSERVICE_WSDL_LOCATION;
    }

}
